### ISSUE TITLE
Configurar GitPages

### ISSUE THREAD

**Issue by roginaldosemog** [fga-eps-mds/2019.2-Grupo7#6]
Configurar GitPage do projeto, para organizar disposição e organização dos documentos e informações à respeito do projeto.

**Tarefas**
- [x] Instalar mkdocs
- [x] Configurar páginas do projeto
- [x] Configurar tema
- [x] Adicionar link da página na descrição do projeto

**Critérios de aceitação**
- [x] Passar nas tarefas acima

**Comment by WillAllmeida** [comment]
Está disponível em: https://fga-eps-mds.github.io/2019.2-Grupo7/

**Comment by roginaldosemog** [comment]
Todas mudanças foram submetidas à master através do pull request #9
